name: main
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: haxelib
        shell: cmd
        run: |
          .\Main.exe setup ${{ github.workspace }}\haxe\lib
          .\Main.exe install systools