name: main
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: haxelib
        shell: cmd
        run: |
          ${{ github.workspace }}\Main.exe setup ${{ github.workspace }}\haxe\lib
          ${{ github.workspace }}\Main.exe install systools