name: main
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: haxelib
        shell: cmd
        run: |
          ./Main.exe setup ${{ github.workspace }}\haxe\lib
          ./Main install systools